In [1]:
import torch
import torchvision

In [2]:
# 构造一个随机初始化矩阵
x = torch.rand(5, 3)
print(x)
# 基于已经存在的tensor创建tensor
x_new = torch.randn_like(x, dtype=torch.float)
print(x_new)
print(x.size())

tensor([[0.5034, 0.2067, 0.8391],
        [0.2975, 0.5259, 0.0759],
        [0.3951, 0.6056, 0.2864],
        [0.9380, 0.6595, 0.2534],
        [0.4203, 0.5969, 0.6932]])
tensor([[ 1.2247,  0.0565, -1.7756],
        [-0.7128, -0.0162,  1.6106],
        [-1.2693, -1.4401,  1.5197],
        [-0.8341,  1.5306, -0.2659],
        [-0.2251,  0.8905, -0.0572]])
torch.Size([5, 3])


In [3]:
# in-place加法
y = torch.ones(5, 3)
y.add_(x)
print(y)

tensor([[1.5034, 1.2067, 1.8391],
        [1.2975, 1.5259, 1.0759],
        [1.3951, 1.6056, 1.2864],
        [1.9380, 1.6595, 1.2534],
        [1.4203, 1.5969, 1.6932]])


In [4]:
# 改变tensor的形状
x = torch.randn(4, 4)
y = x.view(1, 16)
z = x.view(-1, 8)
w = x.view(16)
print(x.size(), y.size(), z.size(), w.size())

torch.Size([4, 4]) torch.Size([1, 16]) torch.Size([2, 8]) torch.Size([16])
